# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates (00:00 UTC each day)
  schedule: [{ cron: '0 0 * * *' }]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: { branches: ['master'] }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: 📊 Isometric Calender
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: isocalender.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ''
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
